version: "2"
services:
    nginx:
        image: nginx-base
        network_mode: "host"
        container_name: "nginx_server"
        ports:
            - "80:80"
        depends_on:
            - "php"
        volumes:
            # todo[改] 配置
            - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./conf/nginx/blog.conf:/etc/nginx/conf.d/blog.conf"
            # todo[改] 源码
            - "/project/solution:/srv/www/vhosts/blog"
            # todo[改] 日志
            - "./log/nginx:/var/log/nginx"

    mysql:
        image: mysql-base
        network_mode: "host"
        container_name: "mysql_server"
        ports:
            - "3306:3306"
        environment:
            #MYSQL_USER: root
            #MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            # todo[改] 配置
            - "./conf/mysql/my.cnf:/etc/my.cnf:ro"
            # todo[改] 数据
            - "./data/mysql:/var/lib/mysql"
            # todo[改] pid
            - "./run/mysql:/var/run/mysql"

    php:
        image: php-base
        network_mode: "host"
        container_name: "php_server"
        ports:
            - "9000:9000"
        volumes:
            # todo[改] 配置
            - "./conf/php/php.ini:/usr/local/etc/php/php.ini"
            - "./conf/php/conf.d/extension.ini:/usr/local/etc/php/conf.d/extension.ini"
            - "./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.conf"
            - "./conf/php/pool.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
            # todo[改] 源码
            - "/project/solution:/srv/www/vhosts/blog"
            # 自定义扩展
            - "./lib/php/my_dynamic.so:/usr/local/lib/php/extensions/no-debug-non-zts-20170718/my_dynamic.so"
            # todo[改] 日志
            - "./log/php:/var/log/php"